### PR TITLE
Adding docker image, and script to run with it

### PR DESCRIPTION
**Pull request by fruch**
TODOs:
- [x] handle relocatable packages
- [x] versions in dockerhub

### CODE REVIEW

**Comment by fruch** [comment]
@roydahan @bentsi 
can you grant correct permissions on this repo for the whole team ?

@hagitsegev 
you can take this branch for a ride if you want

**Comment by roydahan** [comment]
Even I'm not an admin here.

**Comment by avikivity** [comment]
@roydahan added you

**Comment by avikivity** [comment]
for the rest, I'll need docker hub IDs

**Comment by fruch** [comment]
this is actually depends on https://github.com/scylladb/scylla-ccm/pull/163, since I'm using python3 in docker

**Comment by hagitsegev** [comment]
Running: https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/python-driver-matrix-debug/41/

**Pull request merged**
