### PR TITLE
upgrade(requirements.txt): Upgrading Python's packages

### PR DESCRIPTION
**Pull request by Orenef11**

### CODE REVIEW

**Comment by Orenef11** [comment]
@fruch
Do you think we need to upgrade those packages?

**Comment by Orenef11** [comment]
> @fruch Do you think we need to upgrade those packages?

ping

**Comment by fruch** [comment]
> @fruch Do you think we need to upgrade those packages?

Why do you need to upgrade them ? 
Did you tested with them upgraded ?

**Comment by Orenef11** [comment]
> > @fruch Do you think we need to upgrade those packages?
> 
> Why do you need to upgrade them?

I use Pytest to run the test, and I want to create a new docker with the latest package versions.

> Did you tested with them upgraded ?

I checked a few tests and saw that they passed.

**Comment by Orenef11** [comment]
@fruch 
Thanks for you created a new image version.
I'm checking that the new version has not broken the pipeline of the job.
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/Oren/job/python-driver-matrix-test1/14/

**Pull request merged**
