### PR TITLE
scylla: add patch for 3.26.3

### LINKED ISSUE #65: 3.26.3-scylla is failing in patch
3.26.3-scylla was released yesterday

And it's failing the patch

```
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/main.py", line 23, in main
    result = Run(python_driver_git=arguments.python_driver_git,
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 173, in run
    if self._checkout_branch() and self._apply_patch_files() and self._install_python_requirements():
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 108, in _apply_patch_files
    self._run_command_in_shell(f"git apply --check {file_path}")
  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 98, in _run_command_in_shell
    assert status_code == 0, stderr
AssertionError: (None, b'/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\nerror: patch failed: tests/integration/__init__.py:366\nerror: tests/integration/__init__.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_authentication_misconfiguration.py:38\nerror: tests/integration/standard/test_authentication_misconfiguration.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_client_warnings.py:27\nerror: tests/integration/standard/test_client_warnings.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_cluster.py:290\nerror: tests/integration/standard/test_cluster.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_custom_payload.py:43\nerror: tests/integration/standard/test_custom_payload.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_metadata.py:474\nerror: tests/integration/standard/test_metadata.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_query.py:957\nerror: tests/integration/standard/test_query.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_shard_aware.py:188\nerror: tests/integration/standard/test_shard_aware.py: patch does not apply\nerror: patch failed: tests/integration/standard/test_types.py:731\nerror: tests/integration/standard/test_types.py: patch does not apply\n')
```

### PR DESCRIPTION
**Pull request by k0machi**
This change introduces a patch for scylla 3.26.3 driver.

Fixes #65

ToDo:
 * [x] Run a staging job for this commit

### CODE REVIEW

**Comment by fruch** [comment]
> [Job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/argus-python-driver-matrix-test/25/) here.

@k0machi 
Job failed checking out the code

**Comment by k0machi** [comment]
> > [Job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/argus-python-driver-matrix-test/25/) here.
> 
> @k0machi Job failed checking out the code

@fruch Fixed, forgot to change the releng branch

**Comment by k0machi** [comment]
```
17:56:47  ==== 17 failed, 272 passed, 108 skipped, 320 warnings in 4108.54s (1:08:28) ====
17:56:47  INFO:root:=== (scylla:3.26.3-scylla) PYTHON DRIVER MATRIX RESULTS FOR PROTOCOL v4 ===
17:56:47  INFO:root:tests: 397, errors: 0, failures: 1, skipped: 90, xpassed: 7, xfailed: 0, passed: 265, ignored_in_analysis: 34, flaky: 0
17:56:47  ERROR:root:Please check the report because there were failed tests
```

**Comment by fruch** [comment]
> ```
> 17:56:47  ==== 17 failed, 272 passed, 108 skipped, 320 warnings in 4108.54s (1:08:28) ====
> 17:56:47  INFO:root:=== (scylla:3.26.3-scylla) PYTHON DRIVER MATRIX RESULTS FOR PROTOCOL v4 ===
> 17:56:47  INFO:root:tests: 397, errors: 0, failures: 1, skipped: 90, xpassed: 7, xfailed: 0, passed: 265, ignored_in_analysis: 34, flaky: 0
> 17:56:47  ERROR:root:Please check the report because there were failed tests
> ```
> 
> Why does it show different counters?
Before and after applying the skip list 

> 
> Failure is `test_metadata_with_quoted_identifiers`, known issue
>

**Pull request merged**
