### PR TITLE
fix(versions/ main.py run.py): Make python-driver-matrix work

### PR DESCRIPTION
**Pull request by dkropachev**
This fix addresses following issues:
1. Fixes python-driver-matrix test. Currently it does not work
2. Implement driver types, so that we could test different types of dirvers

### CODE REVIEW

**Comment by fruch** [comment]
why we have duplication of `versions/datastax` and `versions/cassandra`, from my POV this is exactly the same versions...

**Comment by dkropachev** [comment]
> why we have duplication of `versions/datastax` and `versions/cassandra`, from my POV this is exactly the same versions...

fixed.

**Comment by fruch** [comment]
@dkropachev do we need change in scylla-pkg pipeline, cause of this PR ? at least to change the defaults version to be tested ?

**Comment by dkropachev** [comment]
@fruch , there is already PR for that - https://github.com/scylladb/scylla-pkg/pull/1466, it does not work at the moment anyway, so it is not going to break a thing in there.

**Pull request merged**
